### ISSUE TITLE
PRIMARY_KEY needs to be changed to PRIMARY KEY in setup.php

### ISSUE THREAD

**Issue by codeandbattle** [DanWin/onion-link-list#10]
setup.php is throwing an error when you try to run it due to the PRIMARY KEY having a underscore between the words on line 55. Remove the underscore and add a space and it seems to work again.

**Comment by DanWin** [comment]
Thanks for the hint. I haven't updated the sources in a long time and I had fixed this issue locally a while ago already. I just published the latest code in eb412415ea35483a0ae0499ab0a40761bdbed748
