### ISSUE TITLE
No captcha table made in setup.php

### ISSUE THREAD

**Issue by codeandbattle** [DanWin/onion-link-list#12]
`Warning: PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dataset.torcheck_captcha' doesn't exist in /var/www/hs/torcheck/onions.php on line 459`

It appears that there is no table made when you run setup.php for the new captcha table.

**Comment by DanWin** [comment]
Thanks for the hint, fixed in 7610c40e8d139be9c51b30501d56d6950ab44f29
