### ISSUE TITLE
Can't get test.php to work properly

### ISSUE THREAD

**Issue by ghost** [DanWin/onion-link-list#14]
My Tor service is enabled and running, but when I try testing a .onion that is obviously online, it always says 'No, the service is offline!'.  When I execute `curl --socks5-hostname 127.0.0.1:9050 http://sitethatisobviouslyonline.onion` from my console it does work. I've already changed `curl_setopt($ch, CURLOPT_PROXYTYPE, 7);` to `curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5_HOSTNAME);` in test.php. What else can I do to fix it? Using nginx/Debian 10/PHP 7.2.

PS: When it says 'No, the service is offline!', it also automatically removes the .onion from the list instead of just displaying a red square that says it's offline. How do I change this behavior?

**Comment by ghost** [comment]
Fixed the first part by uncommenting the `//` lines in test.php. However I would still like it if .onions **don't** automatically get deleted if they are offline.

**Comment by DanWin** [comment]
Thanks for the hint @GarfieldsPipe, I have now replaced those static integers with `CURLPROXY_SOCKS5_HOSTNAME` in 0e221ec.
As for auto-deletion. That happens by default after one month of not being online. If the site was never online or has been offline for more than a week, it will be moved to the offline section.
