### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by ghost** [DanWin/onion-link-list#22]
After editing common_config.php I'm executing `php setup.php` in my server console and get this error:

```
PHP Warning:  PDO::exec(): SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'value' (max = 16383); use BLOB or TEXT instead in /var/www/html/setup.php on line 56
PHP Warning:  PDOStatement::execute(): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'list.settings' doesn't exist in /var/www/html/setup.php on line 58
PHP Notice:  Undefined index: succdbcreate in /var/www/html/setup.php on line 59
```

Using PHP 7.3 and MariaDB 10.6 on Debian 10.

**Comment by GarfieldsPipe** [comment]
@DanWin

**Comment by ghost** [comment]
@DanWin

**Comment by DanWin** [comment]
Thanks for reporting it. You've encountered this, because you are running MySQL in strict mode, which enforces a limit on the length possible in a varchar field. Since we are not currently using the settings table for anything but the schema version, I've reduced the length to varchar(255)
