### ISSUE TITLE
update.php doesn't work when using strict SQL mode

### ISSUE THREAD

**Issue by ghost** [DanWin/onion-link-list#24]
PHP Warning:  PDOStatement::execute(): SQLSTATE[HY000]: General error: 1364 Field 'description' doesn't have a default value in /var/www/html/cron/update.php on line 94

**Comment by ghost** [comment]
This error doesn't happen when disabling MariaDB's strict mode. I'll leave it up to you whether you still want to do anything about this or not.

**Comment by tencentemr** [comment]
same here
