### ISSUE TITLE
F3-Thinker

### ISSUE THREAD

**Issue by alx-xlx** [DanWin/onion-link-list#31]
Hey @DanWin 

a while ago, around 2020 or before. You had added a wonderful onion website on your https://onions.danwin1210.de
Its name was 5pxgor7yuvsjafwr.onion - Freedom of Information (F3Thinker), There weren't many books, but it had some unique books. I had downloaded some of them but forgot to backup the rest. 

Is there by any chance I can get hold of the website again ?

**Comment by DanWin** [comment]
Hello @alx-xlx
It was re-uploaded to other hosts in the past, but I'm not aware of this site still existing.

**Comment by DanWin** [comment]
Hello @alx-xlx ,

I just heard back from the owner of the site. The library isn't online at the moment, but there is a video site https://www.bitchute.com/channel/KFzBdOZqzGTz/

**Comment by alx-xlx** [comment]
@DanWin Thanks for the information sir, I really appreciate you taking your time to reply back.
I wish they made the library online.
